name: Build Action
on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch
        type: string
        default: main
        required: true
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v5
      with:
        ref: ${{ inputs.ref }}
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        npm ci
    - name: Build Action
      run: |
        npm run build
    - name: Update dist
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./dist &&
        git commit -m "Update dist"
        git push origin HEAD:${{ inputs.ref }}
